package com.anandhavalli.quickquote.constants;

public class QuoteClass {

    public static final String[] QUOTES = {
            "Anyone who has never made a mistake has never tried anything new.",
            "Imagination is more important than knowledge.",
            "No problem can be solved from the same level of consciousness that created it.",
            "There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.",
            "Insanity: doing the same thing over and over again and expecting different results.",
            "Be not afraid of greatness: some are born great, some achieve greatness, and some have greatness thrust upon them.",
            "Cowards die many times before their deaths; the valiant never taste of death but once.",
            "We are what our thoughts have made us; so take care about what you think. Words are secondary. Thoughts live; they travel far.",
            "Truth can be stated in a thousand different ways, yet each one can be true.",
            "Don’t take rest after your first victory because if you fail in second, more lips are waiting to say that your first victory was just luck.",
            "Man needs difficulties in life because they are necessary to enjoy the success.",
            "All of us do not have equal talent. But , all of us have an equal opportunity to develop our talents.",
            "Without your involvement you can't succeed. With your involvement you can't fail.",
            "You will not be punished for your anger, you will be punished by your anger.",
            "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.",
            "Holding on to anger is like grasping a hot coal with the intent of throwing it at someone else; you are the one who gets burned.",
            "No one saves us but ourselves. No one can and no one may. We ourselves must walk the path.",
            "Three things cannot be long hidden: the sun, the moon, and the truth.",
            "We are shaped by our thoughts; we become what we think. When the mind is pure, joy follows like a shadow that never leaves.",
            "Peace comes from within. Do not seek it without.",
            "The mind is everything. What you think you become.",
            "Whatever words we utter should be chosen with care for people will hear them and be influenced by them for good or ill.",
            "There are only two mistakes one can make along the road to truth; not going all the way, and not starting.",
            "Even death is not to be feared by one who has lived wisely.",
            "Mirrors can’t talk, lucky for you they can’t laugh either.",
            "Light travels faster than sound. This is why some people appear bright until they speak.",
            "I’m sorry, while you were talking I was trying to figure where the hell you got the idea I cared.",
            "You’re unique just like everyone else!",
            "Find your patience before I lose mine.",
            "Tell me how I have upset you, because I want to know how to do it again.",
            "You always do me a favor, when you shut up!",
            "Are you really stupid or you are just pretending?",
            "Don’t take yourself so seriously, no one else does.",
            "You only live once but if you do it right ONCE IS ENOUGH!!!",
            "We choose our joys and sorrows long before we experience them.",
            "Far better to live our own path imperfectly than to live another's perfectly;).",
            "The quieter you become the more you hear;););). ",
            "To understand the heartb and mind of a person,look not what he has already achieved,but at what he aspires to.",
            "Nothing is impossible;the word itself says \"I'm possible\" .",
            "Normal is an illusion. What is normal for a spider is choas for a fly.",
            "There is no path to happiness ...Happiness is a path",
            "Never reply \"WHEN YOU ARE ANGRY\"...Never make a promise \"WHEN YOU ARE HAPPY\"...Never make a descision \"WHEN YOU ARE SAD\"...",
            "Silence is the music of wisdom.",
            "Don't give up .Beginning is always the hardest.",
            "Courage isn't having the strength to go on" +
                    "- it is going on when you don't have strength.",
            "When you love a person all fear disappears.And when you are afraid all love disappears.",
            "If we are not a little bit uncomfortable every day,we're not growing...All the good stuff is outside our comfort zone.",
            "Start by doing what is necesssary; then do what's possible; and suddenly you are impossible.",
            "Look at what you've got and make the best of it.It is better to light a candle than to curse the darkness.",
            "If you don't stand for something you will fall for anything!!!",
            "Whatever the mind can concieve and believe the mind can achieve.",
            "Well doneis better than well said.",
            "You can do anything ifyou have enthusiasm.",
            "The only person you should try to be better than is the person you were yesterday.",
            "Don't give up what tou want most , for what you want now.",
            "Not all have special talents,some are passionately curious.",
            "One who seeks perfection in a friend will stay without friends.",
            "Once we accept our limits,we go beyond them.",
            "Hear no evil,Speak no evil-And You'll never be invited to a party.",
            "If you work without love you are working like a slave.When you work with love, you work like an emperor.Your workis your joy",
            "Everybody is a genius .But if you judge a fish by its ability to climd a tree,it will ive its whole life believing that it is stupid",
            "Courage isn't having the strength to go on... it is going on when you don't have strength. ",
            "Beauty attracts the eye but personality captures the heart.",
            "Don't work so hard that you stop loving what you do...",
            "STUPID-Knowing the truth,Seeing the truth,but still believing the lies.",
            "Secret of happieness is to have a bad memory",
            "The minute you think of giving up,think of the reason why you held on so long.",
            "No one is useless ,some are used less."
    };

}